name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REACT_APP_SALT: ${{ secrets.REACT_APP_SALT }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run test
